name: EIYARO Main Workflow

defaults:
  run:
    shell: bash

permissions:
  contents: write

on:

  push:
    branches: [ main ]
    tags: [ "*" ]
    paths-ignore: [ "README.md", "CHANGELOG.md", "cliff.toml" ]

  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build Applications
    with:
      fail-fast: false
    runs-on: ${{ matrix.operating-system }}

    strategy:
      matrix:
        operating-system: [ubuntu-latest,windows-latest,macos-latest]

    steps:
      name: Checkput
      uses: actions/checkout@v3

      name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

      name: Build Server
      run: make eiyarod

      name: Build Client
      run: make eiyarocli

  release:
    if: contains(github.ref_type, 'tag')

    name: Create GitHub Release
    needs: [ build ]
    with:
      fail-fast: false

    name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        submodules: true

    name: Build Release
      run: make release-all

    name: Create GitHub release
    uses: softprops/action-gh-release@v1
    with:
      name: EIYARO ${{ env.tag }}
      body: ${{ steps.git-cliff.outputs.content }}
      files: target/*
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
